services:
  app:
    build: app
    restart: unless-stopped
    volumes:
      - ./app:/app
    ports:
      - 7777:7777
    depends_on:
      - database
    env_file:
      - database.env

  database:
    container_name: "postgres-database"
    image: "postgres:13.4"
    restart: unless-stopped
    env_file:
      - database.env

  flyway:
    image: flyway/flyway:7.3.0-alpine
    env_file:
      - database.env
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate